hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/tms
hibernate.connection.username=postgres
hibernate.connection.password=admin
hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
hibernate.show_sql=true
hibernate.current_session_context_class=thread